### ISSUE TITLE
PIP dependency issue

### ISSUE THREAD

**Issue by k3mpaxl** [alexhartm/tonie-podcast-sync#1]
Hi, first thanks for sharing your repo. I found that lxml package required for parsing the podcast xml is missing and should be added to the pip dependencies.

Tested on a fresh ubuntu today. Enabling logging showed me the error like shown here:

https://stackoverflow.com/questions/24398302/bs4-featurenotfound-couldnt-find-a-tree-builder-with-the-features-you-requeste

Have a nice day!
k3mpaxl

**Comment by MaStr** [comment]
Thanks for that hint.
I used the ubuntu based version instead of pip to get it working:

```
sudo apt install python3-bs4 python3-lxml
```

**Comment by alexhartm** [comment]
Thanks for the hint! I added lxml to the poetry depencency list and published a new version to pypi. It seems to work for me, but let me know if you still face issues.
You should be able to upgrade to this new version via `pip install tonie-podcast-sync==1.0.2`
