### ISSUE TITLE
AttributeError: 'ToniePodcastSync' object has no attribute 'sync_podcast_to_tonie' AND ImportError: cannot import name 'EpisodeSorting' from 'toniepodcastsync' (/home/pi/.local/lib/python3.9/site-packages/toniepodcastsync.py)

### ISSUE THREAD

**Issue by HoMarLev** [alexhartm/tonie-podcast-sync#23]
Synchronising command and Podcast import are not working.

Hi there, thank you for the Great work. 

If I take the example file and run it with my credentials two errors appear. The Podcast sorting function and the syncing function are not working properly. Is this a common issue?

**Comment by alexhartm** [comment]
It looks like you have a python 3.9 setup running. There was a larger refactoring for version 2.x of `tonie-podcast-sync`, including changes in the interfaces. With that, a newer python version is now required - at least `3.10.11` or higher.

I suspect that pip on your machine has selected an older version of `tonie-podcast-sync` which could still run in your python environment. 

Could you that which version is installed? (via `pip list | grep tonie-podcast-sync`)

**Comment by HoMarLev** [comment]
Right! Thanks, I am using an outdated version. Works like charm now.
