### ISSUE TITLE
I'm having issues using podcasts from the BR mediathek -> 'latin-1' codec can't encode character

### ISSUE THREAD

**Issue by Zorrensen** [alexhartm/tonie-podcast-sync#26]
First of all, many thanks for this script! 

I first installed the "Maus" podcast, which worked perfect.

When using any podcasts from the BR Mediathek (Anna und die wilden Tiere / Pumuckl etc.), the following problem occurs during the update/download:

`'latin-1' codec can't encode character ' u2026' in position 113 ordinal not in range(256)`

There is probably something in the feed.xml that the script cannot read. I'm hoping for a workaround.

Thank you!

**Comment by alexhartm** [comment]
Hi @Zorrensen 

I just tested it on my computer with the following BR podcasts

´´´
checkertobi = Podcast("https://feeds.br.de/checkpod-der-podcast-mit-checker-tobi/feed.xml")
anne_und_die_wilden_tiere = Podcast("https://feeds.br.de/anna-und-die-wilden-tiere/feed.xml")
lachlabor = Podcast("https://feeds.br.de/lachlabor/feed.xml")
´´´

and those worked so far. So I think the feed.xml files in general are parsed correctly. To investigate this, could you...

- look up which version of tonie-podcast-sync you are using (check by entering `pip list | grep tonie-podcast-sync` in a terminal)
- check if are the URLs of the Podcasts set correctly? u2026 seems to refer to [the unicode character for `...`](https://www.unicodepedia.com/unicode/general-punctuation/2026/horizontal-ellipsis/)
- let me know on which operating system you are running this? (I can only test MacOS and Linux here...)

**Comment by Zorrensen** [comment]
Hi @alexhartm

thanks for your answer!

I am using a raspberry pi 4B 
with Raspbian (64Bit)
Python 3.11.2

tonie-podcast-sync 3.0.0

**Comment by alexhartm** [comment]
Hi @Zorrensen Thanks for the infos, that helped me narrow it down a bit. I think this might be environment related in your case. With raspbian, it should work just fine in general. I'm also using this on Raspbian (on a Pi Zero2). 

I could reproduce your issue when I executed a test script (`test.py`) by running it with a different python IO encoding:

```bash
PYTHONIOENCODING=latin-1 ./test.py
```

Then, I faced the same error. 

I think the root cause is that in your environment, the encoding is somehow altered from utf-8 to latin-1.  As a test, you could do

```bash
export PYTHONIOENCODING=utf-8
```

and then check if this makes it work. (Note that this just sets `PYTHONIOENCODING` for the current session only. After terminal restart, it will revert back to its old value again.)

If that does indeed solve it, you might want to investigate where the encoding is changed to latin-1 and revert that to utf-8 in general. 
If you can't find the specific point where it is set, you could just add  `export PYTHONIOENCODING=utf-8` to your `~/.bashrc` file (open it with e.g. `nano ~/.bashrc`, change it to utf-8, save and restart your terminal). This would set the value automatically every time you log in.

I hope that helps!

**Comment by Zorrensen** [comment]
Thx for your help!

The output looks in CLI looks abit weird now, but it worked!

This is how the uploading process looked after using utf-8 

`Anna und die wilden Tiere: Cache episodes ... Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢ÂºÃ¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢  33% -:--:-Anna und die wilden Tiere: Cache episodes ... Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢ÂºÃ¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢  33% -:--:-Anna und die wilden Tiere: Cache episodes ... Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢ÂºÃ¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢  33% -:--:-Anna und die wilden Tiere: Cache episodes ... Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢ÂºÃ¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢  33% -:--:-Anna und die wilden Tiere: Cache episodes ... Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢ÂºÃ¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢  33% -:--:-Anna und die wilden Tiere: Cache episodes ... Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢ÂºÃ¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢  33% -:--:-Anna und die wilden Tiere: Cache episodes ... Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢ÂºÃ¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢  33% -:--:-Anna und die wilden Tiere: Cache episodes ... Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢ÂºÃ¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢  33% -:--:-Anna und die wilden Tiere: Cache episodes ... Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢ÂºÃ¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢  33% -:--:-Anna und die wilden Tiere: Cache episodes ... Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢ÂºÃ¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢  33% -:--:-Anna und die wilden Tiere: Cache episodes ... Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢ÂºÃ¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢  33% -:--:-Anna und die wilden Tiere: Cache episodes ... Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢ÂºÃ¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢  33% -:--:-Anna und die wilden Tiere: Cache episodes ... Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢ÂºÃ¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢  33% -:--:-Anna und die wilden Tiere: Cache episodes ... Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢ÂºÃ¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢  33% -:--:-Anna und die wilden Tiere: Cache episodes ... Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢ÂºÃ¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢  33% -:--:-Anna und die wilden Tiere: Cache episodes ... Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢ÂºÃ¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢  33% -:--:-Anna und die wilden Tiere: Cache episodes ... Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢ÂºÃ¢Ã¢Ã¢Ã¢Ã¢Ã¢  67% 0:00:0Anna und die wilden Tiere: Cache episodes ... Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢ÂºÃ¢Ã¢Ã¢Ã¢Ã¢Ã¢  67% 0:00:0Anna und die wilden Tiere: Cache episodes ... Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢ÂºÃ¢Ã¢Ã¢Ã¢Ã¢Ã¢  67% 0:00:0Anna und die wilden Tiere: Cache episodes ... Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢ÂºÃ¢Ã¢Ã¢Ã¢Ã¢Ã¢  67% 0:00:0Anna und die wilden Tiere: Cache episodes ... Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢ÂºÃ¢Ã¢Ã¢Ã¢Ã¢Ã¢  67% 0:00:0Anna und die wilden Tiere: Cache episodes ... Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢ÂºÃ¢Ã¢Ã¢Ã¢Ã¢Ã¢  67% 0:00:0Anna und die wilden Tiere: Cache episodes ... Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢ÂºÃ¢Ã¢Ã¢Ã¢Ã¢Ã¢  67% 0:00:0Anna und die wilden Tiere: Cache episodes ... Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢ÂºÃ¢Ã¢Ã¢Ã¢Ã¢Ã¢  67% 0:00:0Anna und die wilden Tiere: Cache episodes ... Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢ÂºÃ¢Ã¢Ã¢Ã¢Ã¢Ã¢  67% 0:00:0Anna und die wilden Tiere: Cache episodes ... Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢ÂºÃ¢Ã¢Ã¢Ã¢Ã¢Ã¢  67% 0:00:0Anna und die wilden Tiere: Cache episodes ... Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢ÂºÃ¢Ã¢Ã¢Ã¢Ã¢Ã¢  67% 0:00:0Anna und die wilden Tiere: Cache episodes ... Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢ÂºÃ¢Ã¢Ã¢Ã¢Ã¢Ã¢  67% 0:00:0Anna und die wilden Tiere: Cache episodes ... Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢ÂºÃ¢Ã¢Ã¢Ã¢Ã¢Ã¢  67% 0:00:0Anna und die wilden Tiere: Cache episodes ... Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢ÂºÃ¢Ã¢Ã¢Ã¢Ã¢Ã¢  67% 0:00:0Anna und die wilden Tiere: Cache episodes ... Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢ÂºÃ¢Ã¢Ã¢Ã¢Ã¢Ã¢  67% 0:00:0Anna und die wilden Tiere: Cache episodes ... Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢ÂºÃ¢Ã¢Ã¢Ã¢Ã¢Ã¢  67% 0:00:0Anna und die wilden Tiere: transferring 3 episodes to Podcast Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢   0% -:--:Ã¢Anna und die wilden Tiere: transferring 3 episodes to Podcast Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢   0% -:--:Ã¢Anna und die wilden Tiere: transferring 3 episodes to Podcast Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢   0% -:--:Ã¢Anna und die wilden Tiere: transferring 3 episodes to Podcast Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢   0% -:--:Ã¢Anna und die wilden Tiere: transferring 3 episodes to Podcast Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢   0% -:--:Ã¢Anna und die wilden Tiere: transferring 3 episodes to Podcast Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢   0% -:--:Ã¢Anna und die wilden Tiere: transferring 3 episodes to Podcast Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢   0% -:--:Ã¢Anna und die wilden Tiere: transferring 3 episodes to Podcast Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢   0% -:--:Ã¢Anna und die wilden Tiere: transferring 3 episodes to Podcast Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢   0% -:--:Ã¢Anna und die wilden Tiere: transferring 3 episodes to Podcast Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢   0% -:--:Ã¢Anna und die wilden Tiere: transferring 3 episodes to Podcast Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢   0% -:--:Ã¢Anna und die wilden Tiere: transferring 3 episodes to Podcast Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢   0% -:--:Ã¢Anna und die wilden Tiere: transferring 3 episodes to Podcast Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢   0% -:--:Ã¢Anna und die wilden Tiere: transferring 3 episodes to Podcast Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢   0% -:--:Ã¢Anna und die wilden Tiere: transferring 3 episodes to Podcast Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢   0% -:--:Ã¢Anna und die wilden Tiere: transferring 3 episodes to Podcast Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢   0% -:--:Ã¢Anna und die wilden Tiere: transferring 3 episodes to Podcast Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢   0% -:--:Ã¢Anna und die wilden Tiere: transferring 3 episodes to Podcast Ã¢Ã¢Ã¢ÂºÃ¢Ã¢Ã¢  33% -:--:Anna und die wilden Tiere: transferring 3 episodes to Podcast Ã¢Ã¢Ã¢ÂºÃ¢Ã¢Ã¢  33% -:--:Anna und die wilden Tiere: transferring 3 episodes to Podcast Ã¢Ã¢Ã¢ÂºÃ¢Ã¢Ã¢  33% -:--:Anna und die wilden Tiere: transferring 3 episodes to Podcast Ã¢Ã¢Ã¢ÂºÃ¢Ã¢Ã¢  33% -:--:Anna und die wilden Tiere: transferring 3 episodes to Podcast Ã¢Ã¢Ã¢ÂºÃ¢Ã¢Ã¢  33% -:--:Anna und die wilden Tiere: transferring 3 episodes to Podcast Ã¢Ã¢Ã¢ÂºÃ¢Ã¢Ã¢  33% -:--:Anna und die wilden Tiere: transferring 3 episodes to Podcast Ã¢Ã¢Ã¢ÂºÃ¢Ã¢Ã¢  33% -:--:Anna und die wilden Tiere: transferring 3 episodes to Podcast Ã¢Ã¢Ã¢ÂºÃ¢Ã¢Ã¢  33% -:--:Anna und die wilden Tiere: transferring 3 episodes to Podcast Ã¢Ã¢Ã¢ÂºÃ¢Ã¢Ã¢  33% -:--:Anna und die wilden Tiere: transferring 3 episodes to Podcast Ã¢Ã¢Ã¢ÂºÃ¢Ã¢Ã¢  33% -:--:Anna und die wilden Tiere: transferring 3 episodes to Podcast Ã¢Ã¢Ã¢ÂºÃ¢Ã¢Ã¢  33% -:--:Anna und die wilden Tiere: transferring 3 episodes to Podcast Ã¢Ã¢Ã¢ÂºÃ¢Ã¢Ã¢  33% -:--:Anna und die wilden Tiere: transferring 3 episodes to Podcast Ã¢Ã¢Ã¢ÂºÃ¢Ã¢Ã¢  33% -:--:Anna und die wilden Tiere: transferring 3 episodes to Podcast Ã¢Ã¢Ã¢ÂºÃ¢Ã¢Ã¢  33% -:--:Anna und die wilden Tiere: transferring 3 episodes to Podcast Ã¢Ã¢Ã¢ÂºÃ¢Ã¢Ã¢  33% -:--:Anna und die wilden Tiere: transferring 3 episodes to Podcast Ã¢Ã¢Ã¢ÂºÃ¢Ã¢Ã¢  33% -:--:Anna und die wilden Tiere: transferring 3 episodes to Podcast Ã¢Ã¢Ã¢ÂºÃ¢Ã¢Ã¢  33% -:--:Anna und die wilden Tiere: transferring 3 episodes to Podcast Ã¢Ã¢Ã¢ÂºÃ¢Ã¢Ã¢  33% -:--:Anna und die wilden Tiere: transferring 3 episodes to Podcast Ã¢Ã¢Ã¢ÂºÃ¢Ã¢Ã¢  33% -:--:Anna und die wilden Tiere: transferring 3 episodes to Podcast Ã¢Ã¢Ã¢Ã¢Ã¢ÂºÃ¢  67% 0:00:Anna und die wilden Tiere: transferring 3 episodes to Podcast Ã¢Ã¢Ã¢Ã¢Ã¢ÂºÃ¢  67% 0:00:Anna und die wilden Tiere: transferring 3 episodes to Podcast Ã¢Ã¢Ã¢Ã¢Ã¢ÂºÃ¢  67% 0:00:Anna und die wilden Tiere: transferring 3 episodes to Podcast Ã¢Ã¢Ã¢Ã¢Ã¢ÂºÃ¢  67% 0:00:Anna und die wilden Tiere: transferring 3 episodes to Podcast Ã¢Ã¢Ã¢Ã¢Ã¢ÂºÃ¢  67% 0:00:Anna und die wilden Tiere: transferring 3 episodes to Podcast Ã¢Ã¢Ã¢Ã¢Ã¢ÂºÃ¢  67% 0:00:Anna und die wilden Tiere: transferring 3 episodes to Podcast Ã¢Ã¢Ã¢Ã¢Ã¢ÂºÃ¢  67% 0:00:Anna und die wilden Tiere: transferring 3 episodes to Podcast Ã¢Ã¢Ã¢Ã¢Ã¢ÂºÃ¢  67% 0:00:Anna und die wilden Tiere: transferring 3 episodes to Podcast Ã¢Ã¢Ã¢Ã¢Ã¢ÂºÃ¢  67% 0:00:Anna und die wilden Tiere: transferring 3 episodes to Podcast Ã¢Ã¢Ã¢Ã¢Ã¢ÂºÃ¢  67% 0:00:Anna und die wilden Tiere: transferring 3 episodes to Podcast Ã¢Ã¢Ã¢Ã¢Ã¢ÂºÃ¢  67% 0:00:Anna und die wilden Tiere: transferring 3 episodes to Podcast Ã¢Ã¢Ã¢Ã¢Ã¢ÂºÃ¢  67% 0:00:Anna und die wilden Tiere: transferring 3 episodes to Podcast Ã¢Ã¢Ã¢Ã¢Ã¢ÂºÃ¢  67% 0:00:Anna und die wilden Tiere: transferring 3 episodes to Podcast Ã¢Ã¢Ã¢Ã¢Ã¢ÂºÃ¢  67% 0:00:Anna und die wilden Tiere: transferring 3 episodes to Podcast Ã¢Ã¢Ã¢Ã¢Ã¢ÂºÃ¢  67% 0:00:Anna und die wilden Tiere: transferring 3 episodes to Podcast Ã¢Ã¢Ã¢Ã¢Ã¢ÂºÃ¢  67% 0:00:Anna und die wilden Tiere: transferring 3 episodes to Podcast Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢ 100% 0:00:Ã¢Anna und die wilden Tiere: transferring 3 episodes to Podcast Ã¢Ã¢Ã¢Ã¢Ã¢Ã¢ 100% 0:00:Ã¢Anna und die wilden Tiere: Successfully uploaded ['NashÃƒÂ¶rner - vom Kampf gegen 
die Wilderei (Fri, 31 May 2024 06:00:00 +0200)', 'Waldameisen - Haufenweise 
fleiÃƒ(Fri, 24 May 2024 06:00:00 +0200)', 
'WeiÃƒ(Fri, 17 May 2024 
`


Anyway - Thanks again! :)

**Comment by alexhartm** [comment]
Huh, this is indeed weird. I'm not sure why, maybe there is some unusually localization value set. Nevertheless, glad it worked for you! :-)
